### Naive Bayes Implementation

In [1]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
import sys
import numpy as np

In [2]:
X, y = load_iris(return_X_y=True)

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

In [6]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [4.8, 3. , 1.4, 0.1],
       [7.1, 3. , 5.9, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3. , 5.8, 2.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.1, 3.8, 1.6, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6.5, 3.2, 5.1, 2. ],
       [6.7, 3.3, 5.7, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.2, 3.4, 5.4, 2.3],
       [4.9, 3. , 1.4, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [6.9, 3.1, 5.4, 2.1],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.1, 3.5, 1.4, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.5, 2.3, 4. , 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5. , 3.2, 1.2, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.4, 2.9, 4.3, 1.3],
       [5.4, 3.4, 1.5, 0.4],
       [7.7, 2.6, 6.9, 2.3],
       [4.9, 2.4, 3.3, 1. ],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 4.1, 1.5, 0.1],
       [6. , 3. , 4.8, 1.8],
       [5.8, 4. , 1.2, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.1, 3.8, 1.5, 0.3],
       [4.7, 3.2, 1.6, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 2.7, 3.9, 1.2],
       [5.7, 2.6, 3.5, 1. ],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.7, 3. , 5. , 1.7],
       [5. , 3. , 1.6, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.7, 3.1, 5.6, 2.4],
       [5.8, 2.7, 5.1, 1.9],
       [5.1, 3.4, 1.5, 0.2],
       [6.6, 2.9, 4.6, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.3, 4.4, 1.3],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.9, 3.1, 1.5, 0.1],
       [6.3, 2.9, 5.6, 1.8],
       [5.8, 2.7, 4.1, 1. ],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2]])

In [7]:
gnb = GaussianNB()

In [8]:
gnb.fit(X_train, y_train)

GaussianNB()

In [9]:
y_pred = gnb.predict(X_test)

In [10]:
print(accuracy_score(y_test, y_pred))

1.0

In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [12]:
confusion_matrix(y_test, y_pred)

array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 11]])

In [13]:
df = sns.load_dataset("tips")

In [14]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [15]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
# Dependent and Independent Features
X = df[["total_bill", "tip", "smoker", "day", "time", "size"]]
y = df.iloc[:, 2]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [18]:
X_train.shape, y_train.shape

((183, 6), (183,))

In [19]:
X_train.head()

     total_bill   tip smoker   day    time  size
171       15.81  3.16    Yes   Sat  Dinner     2
89        21.16  3.00     No  Thur   Lunch     2
157       25.00  3.75     No   Sun  Dinner     4
219       30.14  3.09    Yes   Sat  Dinner     4
234       15.53  3.00    Yes   Sat  Dinner     2

In [20]:
# Feature Encoding (Label and OneHot Encoding)
onehot = OneHotEncoder()
label_smoker = LabelEncoder()
label_time = LabelEncoder()

In [21]:
X_train["smoker"] = label_smoker.fit_transform(X_train["smoker"])
X_train["time"] = label_time.fit_transform(X_train["time"])

In [22]:
X_train.head()

     total_bill   tip  smoker   day  time  size
171       15.81  3.16       1   Sat     0     2
89        21.16  3.00       0  Thur     1     2
157       25.00  3.75       0   Sun     0     4
219       30.14  3.09       1   Sat     0     4
234       15.53  3.00       1   Sat     0     2

In [23]:
X_test["smoker"] = label_smoker.transform(X_test["smoker"])
X_test["time"] = label_time.transform(X_test["time"])

In [24]:
X_test.head()

     total_bill   tip  smoker  day  time  size
64        17.59  2.64       0  Sat     0     3
63        18.29  3.76       1  Sat     0     4
55        19.49  3.51       0  Sun     0     2
111        7.25  1.00       0  Sat     0     1
225       16.27  2.50       1  Fri     1     2

In [25]:
ct = ColumnTransformer(transformers=[("onehot", OneHotEncoder(drop="first"), [3])], remainder="passthrough")

In [26]:
np.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [27]:
X_test = ct.transform(X_test)

In [28]:
X_train

array([[ 1.  ,  0.  ,  0.  , 15.81,  3.16,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 21.16,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 25.  ,  3.75,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.53,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.47,  3.23,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 32.83,  1.17,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.33,  1.67,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , 28.97,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 15.38,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.51,  1.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 24.59,  3.61,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 14.31,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.64,  1.36,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.81,  5.2 ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 16.45,  2.47,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.37,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.26,  3.25,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  8.51,  1.25,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.59,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.04,  2.24,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 18.43,  3.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 23.68,  3.31,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.26,  2.74,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 19.82,  3.18,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  9.55,  1.45,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.74,  1.44,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  3.21,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 38.01,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 34.63,  3.55,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 28.17,  6.5 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.65,  3.35,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 45.35,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 22.82,  2.18,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 25.56,  4.34,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 35.83,  4.67,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 19.44,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.29,  2.6 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 15.95,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 12.74,  2.01,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 19.08,  1.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.03,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.27,  1.71,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 14.15,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 31.85,  3.18,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  8.52,  1.48,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.46,  2.54,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.83,  3.02,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 12.69,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 12.54,  2.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  3.48,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  4.08,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 20.76,  2.24,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 29.03,  5.92,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 21.5 ,  3.5 ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 50.81, 10.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 11.02,  1.98,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.69,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.49,  2.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 48.27,  6.73,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  7.51,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.45,  3.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  9.68,  1.32,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 19.81,  4.19,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.16,  2.75,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 19.77,  2.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 38.07,  4.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 26.59,  3.41,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , 21.01,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 24.55,  2.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  , 16.32,  4.3 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.43,  2.3 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.77,  1.47,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.95,  2.55,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.99,  1.01,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 22.75,  3.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 40.17,  4.73,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.04,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 28.55,  2.05,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 34.83,  5.17,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 22.67,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 34.3 ,  6.7 ,  0.  ,  1.  ,  6.  ],
       [ 1.  ,  0.  ,  0.  , 39.42,  7.58,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 12.9 ,  1.1 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 27.05,  5.  ,  0.  ,  1.  ,  6.  ],
       [ 0.  ,  0.  ,  1.  , 22.76,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 11.35,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 20.27,  2.83,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 10.34,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.82,  1.75,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  8.77,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.23,  2.01,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 15.98,  2.03,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.42,  1.68,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.28,  2.72,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 40.55,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 38.73,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 20.9 ,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , 22.49,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.27,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 35.26,  5.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 24.08,  2.92,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 26.41,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.63,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.08,  3.15,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 11.69,  2.31,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.58,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.94,  3.06,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.36,  1.64,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 11.17,  1.5 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.07,  1.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.29,  3.71,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.69,  2.31,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 12.26,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  9.94,  1.56,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.51,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 30.46,  2.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  , 11.38,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.78,  3.27,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 21.7 ,  4.3 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.17,  6.5 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 25.71,  4.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 13.81,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.13,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.35,  2.5 ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 18.71,  4.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 14.52,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 20.69,  5.  ,  0.  ,  0.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 24.01,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  , 10.09,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.06,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 31.71,  4.5 ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 41.19,  5.  ,  0.  ,  1.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  , 20.53,  4.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 11.87,  1.63,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 19.65,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.48,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.46,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 10.07,  1.83,  0.  ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 27.18,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 32.9 ,  3.11,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 17.29,  2.71,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 43.11,  5.  ,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 24.27,  2.03,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.31,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  9.78,  1.73,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 12.6 ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 26.86,  3.14,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 27.2 ,  4.  ,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 17.81,  2.34,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 24.52,  3.48,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 16.66,  3.4 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 22.12,  2.88,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.82,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.61,  3.39,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 15.48,  2.02,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.24,  1.76,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 17.47,  3.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 24.71,  5.85,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 28.15,  3.  ,  1.  ,  0.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 12.02,  1.97,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.31,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  2.75,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.89,  5.16,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 14.78,  3.23,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 22.42,  3.48,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  7.56,  1.44,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.07,  1.  ,  1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 28.44,  2.56,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 10.65,  1.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 32.4 ,  6.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  7.25,  5.15,  1.  ,  0.  ,  2.  ]])

In [29]:
X_test

array([[ 1.  ,  0.  ,  0.  , 17.59,  2.64,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.25,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 16.27,  2.5 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  5.75,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  3.08,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.15,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.65,  3.68,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 25.28,  5.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.21,  4.29,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.07,  2.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  1.58,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 30.4 ,  5.6 ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  8.35,  1.5 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 14.  ,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.78,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.1 ,  4.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 30.06,  2.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.92,  4.08,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.04,  1.96,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.51,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.4 ,  2.5 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.16,  2.2 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 29.8 ,  4.2 ,  0.  ,  1.  ,  6.  ],
       [ 0.  ,  1.  ,  0.  , 25.29,  4.71,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.77,  2.23,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 14.73,  2.2 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 12.48,  2.52,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.42,  1.57,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.59,  1.61,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.29,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.39,  2.61,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.93,  3.07,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 10.33,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 48.33,  9.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  , 15.98,  3.  ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  8.58,  1.92,  1.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 12.43,  1.8 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.69,  3.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 29.85,  5.14,  0.  ,  0.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  , 12.76,  2.23,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.97,  3.5 ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.24,  3.76,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 21.58,  3.92,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.07,  3.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 26.88,  3.12,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.89,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.49,  4.06,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 48.17,  5.  ,  0.  ,  0.  ,  6.  ],
       [ 0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.03,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 29.93,  5.07,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 20.69,  2.45,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 14.26,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 12.66,  2.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 27.28,  4.  ,  1.  ,  0.  ,  2.  ]])

In [30]:
gnb.fit(X_train, y_train)

GaussianNB()

In [31]:
y_pred = gnb.predict(X_test)

In [32]:
print(accuracy_score(y_test, y_pred))

0.6065573770491803

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      Female       0.56      0.35      0.43        26
        Male       0.62      0.80      0.70        35

    accuracy                           0.61        61
   macro avg       0.59      0.57      0.56        61
weighted avg       0.60      0.61      0.58        61

In [34]:
gnb.predict([[0, 1, 0, 20.5, 3.5, 1, 0, 4]]) #type: ignore

array(['Male'], dtype='<U6')

### Hyperparameter Tuning

In [35]:
params = {
    "var_smoothing": [1e-9, 1e-8, 1e-7, 1e-6]
}

In [36]:
# Grid SearchCV
grid = GridSearchCV(estimator=gnb, param_grid=params, cv=5)

In [38]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06]})

In [39]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06]})

In [40]:
grid.best_params_

{'var_smoothing': 1e-09}

In [41]:
grid.best_score_

np.float64(0.666066066066066)

In [42]:
y_pred = grid.predict(X_test)

In [43]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      Female       0.56      0.35      0.43        26
        Male       0.62      0.80      0.70        35

    accuracy                           0.61        61
   macro avg       0.59      0.57      0.56        61
weighted avg       0.60      0.61      0.58        61

In [44]:
print(confusion_matrix(y_test, y_pred))

[[ 9 17]
 [ 7 28]]